Сетка страниц
htmlacademy-htmlcss/308327-sedona-37 pull request #6
Opened 2023-06-30 08:57 UTC by Nemchinov01

2023-07-02 08:46 UTC, vadimrahmanov requested changes

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +  background-color: none;
Такого свойства у `background-color` нету. Если необходимо убрать цвет, то задай просто прозрачный цвет (transparent)

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +              <button class="main-header__modal-btn--open" type="button">Хочу сюда!</button>
модификатор не может быть без самого класса элемента. В данном случае класс элемента `main-header__modal-btn`

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +              <div class="options__card-btn--wrapper">
Нету класса элемента, а применён просто модификатор. Ниже такая же проблема.

2023-07-02 08:46 UTC, vadimrahmanov commented on index.html
> +              <button class="main-header__modal-btn--open" type="button">Хочу сюда!</button>
Отсутствует класс элемента.

2023-07-02 08:46 UTC, vadimrahmanov commented on index.html
> +              <img class="advantages__item-image--city" src="images/photo-1.jpg" width="800" height="385"
Модификатор должен сопровождаться классом элемента (`advantages__item-image`)

2023-07-02 08:46 UTC, vadimrahmanov commented on index.html
> +              <img class="advantages__item-image--bridge" src="images/photo-2.jpg" width="800" height="385"
Модификатор должен сопровождаться классом элемента (`advantages__item-image`)

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +              </form>
Если это форма, то она как-то должна отправляться. А здесь нету кнопки `submit`. 
Думаю лучше переделать на ссылку.

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +            <div class="breadcrumbs">
если используешь БЭМ, то здесь стоит добавить ещё спереди класс `filter-aparment__breadcrumbs`. И тогда  получится грамотный микс.

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +            <option value="Популярные">Популярные</option>
Перепиши значения `value` на английский. Если бы это был реальный сайт, то ты бы взаимодействовал здесь с JavaScript, а тащить кириллицу в JS как-то не очень.

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +                <span class="options__card-stars"></span>
Пустой элемент. Поставь сюда текст для доступности. Например span visually-hidden с количеством звёзд. 

Ниже то же самое.

2023-07-02 08:46 UTC, vadimrahmanov commented on catalog.html
> +                <strong class="options__card-cost">От 5000 ₽</strong>
А зачем здесь вообще `strong`? Я знаю, что говорил заменить `<b>` на `strong`, но вот теперь не пойму, а зачем здесь это вообще нужно? :D

2023-07-02 08:46 UTC, vadimrahmanov commented on index.html
> +              </form>
Такая же проблема, что и на странице каталога.

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
>  }
Это лишнее свойство. Элементы `<a>` по-умолчанию имеют такой курсор.

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +}
Если это убрать, то ничего не меняется.

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
Такие свойства можно сокращать следующим образом `grid-template-columns: repeat(3, 1fr);`

Там где 3 - количество, сколько столбиков, затем размер после запятой.

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +}
У тебя кнопка вываливается из контейнера.

![Screenshot 2023-07-02 at 09 38 40](https://github.com/htmlacademy-htmlcss/308327-sedona-37/assets/53314530/726c13b0-9324-428a-95a3-e134501b1cad)

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +  margin-left: 237px;
Лучше задай здесь просто `margin: 0 auto;` а у copyright вообще убери марджин.
А можно вообще эти марджины убрать и задать родителю` justify-content: space-between;`.

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +
Зачем это здесь?

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +  grid-template-columns: 1fr 1fr;
repeat(2, 1fr)

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +}
Здесь не по макету, но я думаю ты когда будешь стилизовать эти блоки, то сам увидишь и исправишь)

2023-07-02 08:46 UTC, vadimrahmanov commented on styles/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
repeat(3, 1fr)

2023-07-02 11:54 UTC, Nemchinov01 commented on catalog.html
> +              </form>
по нажатию на Enter, можно добавить кнопку отправки и скрыть ее, но это избыточно. Очередная ссылка на каталог, ну как то перебор, не?

2023-07-02 11:56 UTC, Nemchinov01 commented on catalog.html
> +              <button class="main-header__modal-btn--open" type="button">Хочу сюда!</button>
Согласен, походу уже бездумно писал

2023-07-02 16:36 UTC, Nemchinov01 commented on catalog.html
> +            <div class="breadcrumbs">
ок

2023-07-02 16:45 UTC, Nemchinov01 commented on catalog.html
> +            <option value="Популярные">Популярные</option>
ок

2023-07-02 16:47 UTC, Nemchinov01 commented on catalog.html
> +              <div class="options__card-btn--wrapper">
ok

2023-07-02 17:26 UTC, Nemchinov01 commented on catalog.html
> +                <span class="options__card-stars"></span>
ок

2023-07-02 17:28 UTC, Nemchinov01 commented on catalog.html
> +                <strong class="options__card-cost">От 5000 ₽</strong>
Удобно стилизовать + без стилей смотрится приемлемо(Цена выделена, находятся на одной строке inline)

2023-07-02 17:36 UTC, Nemchinov01 commented on index.html
> +              </form>
ок

2023-07-02 17:36 UTC, Nemchinov01 commented on index.html
> +              <button class="main-header__modal-btn--open" type="button">Хочу сюда!</button>
ок

2023-07-02 17:44 UTC, Nemchinov01 commented on index.html
> +              <img class="advantages__item-image--city" src="images/photo-1.jpg" width="800" height="385"
ок

2023-07-02 17:44 UTC, Nemchinov01 commented on index.html
> +              <img class="advantages__item-image--bridge" src="images/photo-2.jpg" width="800" height="385"
ок

2023-07-02 17:51 UTC, Nemchinov01 commented on styles/style.css
>  }
Это для того, что бы у тех ссылок у которых не href, курсор не менялся и не отличался от других.

2023-07-02 18:01 UTC, Nemchinov01 commented on styles/style.css
> +}
Sticky footer. Если удалить все наполнениt из main, масштабировать страницу (эмитация изиенения разрешение экрана), то футер всегда будет привязан к низу экрана.(на ретро рассказали, или скринкаст не помню)

2023-07-02 18:02 UTC, Nemchinov01 commented on styles/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
так наглядней, всего 3 колонки) ок

2023-07-02 18:04 UTC, Nemchinov01 commented on styles/style.css
> +}
ok

2023-07-02 18:13 UTC, Nemchinov01 commented on styles/style.css
> +  margin-left: 237px;
ok

2023-07-02 18:14 UTC, Nemchinov01 commented on styles/style.css
> +
sticky footer

2023-07-02 18:15 UTC, Nemchinov01 commented on styles/style.css
> +  grid-template-columns: 1fr 1fr;
ok

2023-07-03 13:37 UTC, vadimrahmanov approved these changes

2023-07-03 13:37 UTC, vadimrahmanov commented on catalog.html
> +              <input class="filter-apartment__form-btn filter-apartment__form-btn--reset" type="reset" value="reset">
Здесь стоит оставить как было, т.к в этом случае value отвечает за то, что будет написано в кнопке

2023-07-03 13:37 UTC, vadimrahmanov commented on catalog.html
> +                <strong class="options__card-cost">От 5000 ₽</strong>
Можно было в таком случае использовать просто span, но в принципе если оставить так, то не должно возникнуть проблем.

2023-07-03 13:37 UTC, vadimrahmanov commented on styles/style.css
> +  min-width: 452px;
В данном случае это прокатит, но когда будет адаптив, то уже таким способом не получится исправить :D

2023-07-03 13:37 UTC, merged